name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    name: Backend (Python)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with Flake8
        run: |
          pip install flake8
          flake8 .

      - name: Run tests
        run: |
          pip install pytest
          pytest

  frontend:
    name: Frontend (Node.js / EJS)
    runs-on: ubuntu-latest
    needs: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        # If your frontend is in a subfolder, add:
        # working-directory: ./path/to/frontend

      - name: Lint with ESLint
        run: npm run lint
        # working-directory: ./path/to/frontend

      - name: Build
        run: npm run build
        # working-directory: ./path/to/frontend
